### ISSUE TITLE
major issue

### ISSUE THREAD

**Issue by pk3zip** [codergautam/swordbattle.io#22]
Hey @codergautam when i get home in a few hours i am dm you on discord a SEVERE vuln that someone could use to get your db

**Comment by pk3zip** [comment]
nvm false alarm

**Comment by codergautam** [comment]
?

**Comment by pk3zip** [comment]
i tried to get him to tell me but he wouldnt

**Comment by codergautam** [comment]
We all know it's you but ok

**Comment by pk3zip** [comment]
you know i like to mess around
