### ISSUE TITLE
Skins don't cost what their listed price is

### ISSUE THREAD

**Issue by ColoredHue** [codergautam/swordbattle.io#51]
- Reported by ioi and wasd. 
- Aerial costs 50k when its supposed to cost 500
- The issue seems to be that Aerial has Aztecs price.
- I checked to make sure by buying bone dragon for 100k, the next skin was Cooler Carl for 1k
- I was only charged 1k
- So the issue is that all the skins have the next skins price

**Comment by codergautam** [comment]
Bro what

**Comment by codergautam** [comment]
fixed btw

**Comment by ImAmethystBladeYT** [comment]
W

**Comment by ColoredHue** [comment]
bro commented on a GitHub issue 😭
